image: Visual Studio 2017
services:
- mssql2017
configuration: Release
platform: Any CPU
install:
- cmd: appveyor downloadfile https://dist.nuget.org/win-x86-commandline/latest/nuget.exe
before_build:
- ps: nuget restore
build:
  verbosity: minimal
test_script:
- cmd: >-
    %xunit20%\xunit.console SqlServer.Native.Tests\bin\Release\net47\SqlServer.Native.Tests.dll

artifacts:
- path: nugets\**\*.nupkg